version: "3.8"

services:
  marketplace:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    working_dir: /code/
    volumes:
      - .:/code
    command: sh -c "yarn install && yarn build:main && cd build && node main/index.js"
    env_file:
      - .env

networks:
  default:
    external:
      name: marketplace-network